### ISSUE TITLE
philosophy

### ISSUE THREAD

**Issue by trinker** [MarcoDVisser/baseGrAid#1]
> set of functions to ease working with base graphics

So you admit it's hard :-)

**Comment by MarcoDVisser** [comment]
Never! It's actually going to be a set of custom functions I've made over the years and I find it silly to copy/paste or source em into my documents when I could just compile them as a package.

But I see that title is misleading... I'll make sure to change it. Damn ggplot2 fanboys ;)

**Comment by trinker** [comment]
:-)
